# Generated by Django 3.1.3 on 2021-01-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Article publication date')),
                ('Paywall', models.BooleanField()),
                ('Title', models.CharField(max_length=200)),
                ('Summary', models.TextField()),
                ('Url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsSource', models.CharField(max_length=200)),
                ('Paywall', models.BooleanField()),
                ('NewsSourceData', models.CharField(max_length=1000)),
            ],
        ),
    ]
