# Generated by Django 3.1.3 on 2021-01-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='Paywall',
            field=models.BooleanField(default=False),
        ),
    ]
