# Generated by Django 3.1.3 on 2021-05-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_newssource_cred'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tempIgnore',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
