# Generated by Django 3.1.3 on 2021-05-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_article_tempignore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tempIgnore',
            new_name='TempIgnore',
        ),
    ]
