# Generated by Django 3.1.3 on 2021-05-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20210522_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='TempIgnore',
            new_name='tempIgnore',
        ),
    ]
