# Generated by Django 3.1.3 on 2021-05-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20210522_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tempIgnore',
        ),
    ]
