# Generated by Django 3.1.3 on 2021-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_newssource_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='monthyViews',
            field=models.FloatField(default=0.1),
        ),
    ]
