# Generated by Django 3.1.3 on 2021-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_newssource_monthyviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
